name: Node.js CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check out code  
      uses: actions/checkout@v4
    - name: print folders
      run: ls  
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: install dependecies    
      run: |
        npm ci
        npm install

    - name: run tests 
      run: |
        npm run test



# name: 04 - Using Actions

# on: workflow_dispatch

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: 04-using-actions/react-app
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20.x'
#       - name: Install Dependencies
#         run: npm ci
#       - name: Run Unit Tests
#         run: npm run test   